### ISSUE TITLE
Add socks5 proxies [tls-client v1.7.0]

### ISSUE THREAD

**Issue by baderdean** [daijro/hrequests#19]
Hello,

everytime I try to use socks5 proxies I got a Connection Error:

```
>>> get(
...     "https://ipv4.webshare.io/",
...     proxies={
...         "http": "socks5h://XXXX-rotate:XXXXX@p.webshare.io:80/",
...         "https": "socks5h://XXXX-rotate:XXXX@p.webshare.io:80/"
...     }
... ).text
Traceback (most recent call last):
  File "/home/bader/code/python3/lib/python3.11/site-packages/hrequests/response.py", line 72, in execute_request
    resp = self.session.execute_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bader/code/python3/lib/python3.11/site-packages/hrequests/client.py", line 389, in execute_request
    raise ClientException(response_object['body'])
hrequests.exceptions.ClientException: failed to build client out of request input: scheme socks5h is not supported

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bader/code/python3/lib/python3.11/site-packages/hrequests/reqs.py", line 209, in request
    req.send()
  File "/home/bader/code/python3/lib/python3.11/site-packages/hrequests/reqs.py", line 126, in send
    raise e
  File "/home/bader/code/python3/lib/python3.11/site-packages/hrequests/reqs.py", line 123, in send
    self.response = self.session.request(self.method, self.url, **merged_kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bader/code/python3/lib/python3.11/site-packages/hrequests/session.py", line 181, in request
    proc.send()
  File "/home/bader/code/python3/lib/python3.11/site-packages/hrequests/response.py", line 65, in send
    self.response = self.execute_request()
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bader/code/python3/lib/python3.11/site-packages/hrequests/response.py", line 80, in execute_request
    raise ClientException('Connection error') from e
hrequests.exceptions.ClientException: Connection error

```

**Comment by daijro** [comment]
Unfortunately socks5h is [not supported by tls-client](https://github.com/bogdanfinn/tls-client/issues/67) due to limitations in Go's backend. There may be a time in the future in which socks5 support is added, but it isn't possible at the moment.

Here is a reference: https://github.com/golang/go/issues/13454

**Comment by baderdean** [comment]
What about socks5 and not socks5h?

**Comment by daijro** [comment]
An experimental socks5 proxy has been added to tls-client [a couple days ago](https://github.com/bogdanfinn/tls-client/commit/577aaa8fa48b14af491f6e661a48fa44906e19b4), and should be rolled out with its next release. This should be added within the next couple of weeks.

**Comment by daijro** [comment]
v0.8.0-beta.2 bumped tls-client up to 1.7.2, so socks5 should work perfectly fine now 👍
