### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by Vitek14** [daijro/hrequests#34]
```C:\Users\Val\Desktop\Python-Learning\playful>python
Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import hrequests
Downloading tls-client library from bogdanfinn/tls-client...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python310\lib\site-packages\hrequests\__init__.py", line 2, in <module>
    from .session import Session, TLSSession, chrome, firefox
  File "C:\Python310\lib\site-packages\hrequests\session.py", line 11, in <module>
    from .cffi import freeMemory
  File "C:\Python310\lib\site-packages\hrequests\cffi.py", line 90, in <module>
    libman = LibraryManager()
  File "C:\Python310\lib\site-packages\hrequests\cffi.py", line 35, in __init__
    filename = self.check_library()
  File "C:\Python310\lib\site-packages\hrequests\cffi.py", line 54, in check_library
    self.download_library()
  File "C:\Python310\lib\site-packages\hrequests\cffi.py", line 63, in download_library
    if self.file_cont in asset['name'] and asset['name'].endswith(self.file_ext):
TypeError: string indices must be integers
```
This also happens when you install both hrequests and hrequests[all]

**Comment by Vitek14** [comment]
I'm not sure how I fixed this, but now the error does not occur anymore.
