### ISSUE TITLE
Browser Session - Error

### ISSUE THREAD

**Issue by yurijserrano** [daijro/hrequests#44]
Good Morning

OS: Ubuntu 20.04

By using the hrequests.firefox.BrowserSession() I am receiving the error:

`on 0: Exception in thread Thread-2 (spawn_main):
Traceback (most recent call last):
  File "/.asdf/installs/python/3.10.5/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
on 0:   File "/.asdf/installs/python/3.10.5/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
on 0:   File "/.asdf/installs/python/3.10.5/lib/python3.10/site-packages/hrequests/browser.py", line 128, in spawn_main
    asyncio.new_event_loop().run_until_complete(self.main())
on 0:   File "/.asdf/installs/python/3.10.5/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
on 0:   File "/.asdf/installs/python/3.10.5/lib/python3.10/site-packages/hrequests/browser.py", line 135, in main
    self.context = await self.client.new_context(
on 0:   File "/.asdf/installs/python/3.10.5/lib/python3.10/site-packages/hrequests/playwright_mock/playwright_mock.py", line 35, in new_context
    _proxy = await ProxyManager(self, proxy)
on 0:   File "/.asdf/installs/python/3.10.5/lib/python3.10/site-packages/async_class.py", line 173, in __await__
    yield from self.create_task(
on 0:   File "/.asdf/installs/python/3.10.5/lib/python3.10/site-packages/hrequests/playwright_mock/proxy_manager.py", line 25, in __ainit__
    self.timeout = httpx.Timeout(20.0, read=None)
on 0: TypeError: Timeout.__init__() got an unexpected keyword argument 'read'
Processing Tags |                                        | ▄▂▂ 0/3 [0%] in 7:48 (~0s, 0.0/s)`

It's related to the dependency and not with the code.

I am reporting for further analysis.

Have a great day.

**Comment by vitalis** [comment]
@yurijserrano is this issue still relevant or can be closed?
