### ISSUE TITLE
Permission denied: browser-helper-file.json

### ISSUE THREAD

**Issue by joerg-claussen** [daijro/hrequests#65]
After upgrading to 0.9.0 I get the following error. The file browser-helper-file.json does not exist in the specified directory.

`2024-11-13, 21:15:15 CET] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "export PYTHONPATH='${PYTHONPATH}:/home/bird/realestatecrawlers/' && /home/bird/miniconda3/envs/realEstateCrawlers/bin/python /home/bird/realestatecrawlers/de/ebay_agents.py"]
[2024-11-13, 21:15:15 CET] {subprocess.py:86} INFO - Output:
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO - browser-helper-file.json ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/? bytes ?
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO - header-network.json      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/? bytes ?
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO - headers-order.json       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/? bytes ?
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO - input-network.json       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/? bytes ?
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO - fingerprint-network.json ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/? bytes ?
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -   File "/home/bird/realestatecrawlers/de/ebay_agents.py", line 2, in <module>
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -     import hrequests as requests
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -   File "/home/bird/miniconda3/envs/realEstateCrawlers/lib/python3.11/site-packages/hrequests/__init__.py", line 33, in <module>
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -     from .session import Session, TLSSession, chrome, firefox
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -   File "/home/bird/miniconda3/envs/realEstateCrawlers/lib/python3.11/site-packages/hrequests/session.py", line 5, in <module>
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -     from browserforge.headers import Browser as BFConstraints
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -   File "/home/bird/miniconda3/envs/realEstateCrawlers/lib/python3.11/site-packages/browserforge/headers/__init__.py", line 3, in <module>
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -     DownloadIfNotExists()
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -   File "/home/bird/miniconda3/envs/realEstateCrawlers/lib/python3.11/site-packages/browserforge/download.py", line 159, in DownloadIfNotExists
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -     Download()
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -   File "/home/bird/miniconda3/envs/realEstateCrawlers/lib/python3.11/site-packages/browserforge/download.py", line 150, in Download
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -     asyncio.run(AsyncDownload(headers=headers, fingerprints=fingerprints))
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -   File "/home/bird/miniconda3/envs/realEstateCrawlers/lib/python3.11/asyncio/runners.py", line 190, in run
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -     return runner.run(main)
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -   File "/home/bird/miniconda3/envs/realEstateCrawlers/lib/python3.11/asyncio/runners.py", line 118, in run
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -     return self._loop.run_until_complete(task)
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -   File "/home/bird/miniconda3/envs/realEstateCrawlers/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -     return future.result()
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -   File "/home/bird/miniconda3/envs/realEstateCrawlers/lib/python3.11/site-packages/browserforge/download.py", line 145, in AsyncDownload
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -     await downloader.download(headers=headers, fingerprints=fingerprints)
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -   File "/home/bird/miniconda3/envs/realEstateCrawlers/lib/python3.11/site-packages/browserforge/download.py", line 137, in download
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -     await asyncio.gather(*tasks)
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -   File "/home/bird/miniconda3/envs/realEstateCrawlers/lib/python3.11/site-packages/browserforge/download.py", line 111, in _download_and_extract
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -     await self._download_file(url, path, progress, task_id, session)
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -   File "/home/bird/miniconda3/envs/realEstateCrawlers/lib/python3.11/site-packages/browserforge/download.py", line 75, in _download_file
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -     async with aiofiles.open(path, 'wb') as fstream:
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -   File "/home/bird/miniconda3/envs/realEstateCrawlers/lib/python3.11/site-packages/aiofiles/base.py", line 63, in __aenter__
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -     return await self
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -            ^^^^^^^^^^
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -   File "/home/bird/miniconda3/envs/realEstateCrawlers/lib/python3.11/site-packages/aiofiles/base.py", line 59, in __await__
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -     self._obj = yield from self._coro.__await__()
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -   File "/home/bird/miniconda3/envs/realEstateCrawlers/lib/python3.11/site-packages/aiofiles/threadpool/__init__.py", line 92, in _open
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -     f = await loop.run_in_executor(executor, cb)
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -   File "/home/bird/miniconda3/envs/realEstateCrawlers/lib/python3.11/concurrent/futures/thread.py", line 58, in run
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -     result = self.fn(*self.args, **self.kwargs)
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-13, 21:15:15 CET] {subprocess.py:93} INFO - PermissionError: [Errno 13] Permission denied: '/home/bird/miniconda3/envs/realEstateCrawlers/lib/python3.11/site-packages/browserforge/headers/data/browser-helper-file.json'
[2024-11-13, 21:15:15 CET] {subprocess.py:97} INFO - Command exited with return code 1`

**Comment by daijro** [comment]
Hello, what version of Browserforge do you have installed?

```
python3 -m pip freeze | grep browserforge
```

**Comment by joerg-claussen** [comment]
I have the latest version installed `browserforge==1.1.2`
