### ISSUE TITLE
'Failed to connect to proxy' error when using IPV6 proxy

### ISSUE THREAD

**Issue by tufkubie** [daijro/hrequests#66]
Hello, 
I have no problem using IPV4 proxy in BrowserSession but I get an error when using IPV6 proxy. (I am trying the latest version 0.9.0)

`Failed to connect to proxy: ...`
> Exception ignored in: <function BrowserSession.__del__ at 0x00000287EA1AF740>
Traceback (most recent call last):
  File "C:\Users\thex\anaconda3\envs\env\Lib\site-packages\hrequests\browser\browser.py", line 610, in __del__
    self.close()
  File "C:\Users\thex\anaconda3\envs\env\Lib\site-packages\hrequests\browser\browser.py", line 596, in close
    cookiejar = self.getCookies()
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\thex\anaconda3\envs\env\Lib\site-packages\hrequests\browser\browser.py", line 401, in getCookies
    browser_cookies: list = self.context.cookies()
                            ^^^^^^^^^^^^
AttributeError: 'BrowserSession' object has no attribute 'context'

**Comment by tufkubie** [comment]
I tried 0.9.1 but same problem. Connection problem when using IPv6 proxy.

**Comment by tufkubie** [comment]
the problem is related to 'geoip' in Camoufox. @daijro
