### ISSUE TITLE
Render Screenshot - page is not fully rendered

### ISSUE THREAD

**Issue by Btibert3** [daijro/hrequests#9]
I was working through the README; excellent package.  In the past I have used playwright to headlessly render a page and take a screenshot.  I attempted to replicate this in your library but the screenshot captured appears to lack the javascript rendering.

```
session = hrequests.Session(browser='chrome')
resp = session.get('https://www.bentley.edu/undergraduate')
page = resp.render(mock_human=True)
page.awaitNavigation()
page.screenshot('test.png', full_page=True)
```

It likely could be user error, but I am not sure what the best path would be to ensure that the page renders before grabbing a screenshot.

**Comment by daijro** [comment]
Hello,

Seems like theres an issue with screenshots on headless Chromium windows. I will look for a fix asap.
Thanks for bringing this up!

**Comment by daijro** [comment]
I haven't been able to consistently reproduce this error, but there is an experimental solution in the latest commit for v0.7.0.

**Comment by Btibert3** [comment]
Great, thank you.

**Comment by franz-see** [comment]
I retried his code and now I am getting this `Cannot use selector and full_page together`

**Comment by Btibert3** [comment]
And FWIW the error @franz-see reported also occurs with Firefox

```
session = hrequests.Session(browser='firefox')
resp = session.get('https://www.bentley.edu/undergraduate')
page = resp.render(mock_human=True)
page.awaitNavigation()
page.screenshot('test.png', full_page=True)
```

which throws

```
Exception in thread Thread-12 (spawn_main):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hrequests/browser.py", line 128, in spawn_main
    asyncio.new_event_loop().run_until_complete(self.main())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/hrequests/browser.py", line 155, in main
    out = await call()
  File "/usr/local/lib/python3.10/dist-packages/hrequests/browser.py", line 413, in _screenshot
    assert not (selector and full_page), 'Cannot use selector and full_page together'
AssertionError: Cannot use selector and full_page together
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
[<ipython-input-10-89893c06cbe2>](https://localhost:8080/#) in <cell line: 5>()
      3 page = resp.render(mock_human=True)
      4 page.awaitNavigation()
----> 5 page.screenshot('test.png', full_page=True)

2 frames
[/usr/lib/python3.10/threading.py](https://localhost:8080/#) in wait(self, timeout)
    318         try:    # restore state no matter what (e.g., KeyboardInterrupt)
    319             if timeout is None:
--> 320                 waiter.acquire()
    321                 gotit = True
    322             else:

KeyboardInterrupt:

```
